In [ ]:
# NAIVE BAYES

# 1.MULTINOMIAL NAIVE BAYES

In [ ]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv("real_drug_dataset.csv")
df

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
2,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
3,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
4,P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3
...,...,...,...,...,...,...,...,...,...
995,P0996,18,Male,Hypertension,Losartan,100,44,Headache,7.7
996,P0997,35,Female,Infection,Azithromycin,50,15,Nausea,5.3
997,P0998,49,Female,Depression,Sertraline,850,52,Dry mouth,8.0
998,P0999,64,Male,Depression,Escitalopram,850,36,Nausea,7.6


In [ ]:
df.isnull().sum()

,0
Patient_ID,0
Age,0
Gender,0
Condition,0
Drug_Name,0
Dosage_mg,0
Treatment_Duration_days,0
Side_Effects,0
Improvement_Score,0


In [ ]:
le=LabelEncoder()

In [ ]:
df["Condition"]=le.fit_transform(df["Condition"])
df["Condition"]

,Condition
0,3
1,2
2,0
3,1
4,0
...,...
995,2
996,3
997,0
998,0


In [ ]:
df["Drug_Name"]=le.fit_transform(df["Drug_Name"])
df["Drug_Name"]

,Drug_Name
0,4
1,11
2,3
3,6
4,3
...,...
995,9
996,2
997,13
998,5


In [ ]:
x=df [["Age","Condition","Drug_Name","Dosage_mg"]]


In [ ]:
y=le.fit_transform(df["Side_Effects"])
y

array([19, 28,  9, 17,  2,  7, 19, 16, 19, 19, 11, 19,  7,  9, 19,  7,  0,
       17,  9, 19,  2, 18, 16,  3, 19,  7, 28, 19, 21, 28,  7, 29, 16, 17,
       14, 17, 17, 11, 19,  6, 29, 26, 14,  4,  1, 10, 20, 11,  4, 27, 16,
        7, 17,  7, 19,  0,  7,  5,  9, 19, 29,  7, 17, 20,  7, 10, 15, 28,
       27, 10,  7, 10, 26, 19, 15, 15,  6, 11, 20,  2, 19, 25,  3,  4,  4,
        2, 19, 15, 19,  9, 19, 29,  8, 13, 10,  6, 10, 11, 21,  2,  1,  6,
       10,  5,  9, 19, 18,  3, 20,  2, 13, 11, 21, 25,  7, 22, 22, 11, 11,
       10,  3, 19, 11, 18,  8,  5, 22, 22,  7,  6,  7, 14,  7, 19, 19, 29,
       27,  7, 19, 14, 26, 29, 10,  8, 19, 25, 17, 15,  4,  7,  4,  6, 19,
       27, 17, 19, 20, 14, 29, 11, 17,  9, 20, 11,  7, 14, 24,  7,  8, 14,
        5, 15,  9,  6, 11, 11, 21, 16, 26, 24,  1,  2,  0, 19,  7,  8, 29,
       29,  9, 11, 25,  4, 13,  6,  0, 19, 21, 19, 19,  7, 11,  7, 13, 24,
        1, 26,  2, 17,  7, 13,  4, 19,  6, 19, 19,  7,  4, 19,  7, 19, 28,
        4, 27, 18,  5, 25

In [ ]:
models=MultinomialNB()
models.fit(x,y)

MultinomialNB()

In [ ]:
test=pd.DataFrame({"Age":[45],"Condition":[1],"Drug_Name":[5],"Dosage_mg":[100]})

In [ ]:
pred=models.predict(test)
pred

array([25])

In [ ]:
print("Predicted side effects:",le.inverse_transform(pred)[0])

Predicted side effects: Stomach upset


In [ ]:
# 2.GAUSSIAN NAIVE BAYES

In [ ]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [ ]:
data=pd.read_csv("IRIS.csv")
data

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [ ]:
data.isnull().sum()

,0
sepal_length,0
sepal_width,0
petal_length,0
petal_width,0
species,0


In [ ]:
data["species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x=data[["sepal_length","sepal_width","petal_length","petal_width"]]
y=data[["species"]]

In [ ]:
i_model=GaussianNB()

In [ ]:
i_model.fit(X_train,Y_train)

GaussianNB()

In [ ]:
y_pred=i_model.predict(X_test)
y_pred

array([29, 17,  4, 25,  1,  1,  2,  0,  3, 27, 22,  1, 28, 27,  1, 14,  3,
        1, 16,  2, 25,  3, 17,  1,  4,  0,  1,  1,  4, 24, 17, 14,  1,  1,
       12, 26, 15, 15, 27, 15,  3, 27, 25, 25, 18, 17, 15, 23, 17,  1, 27,
       18, 27, 25,  3, 15,  1,  2,  4, 17, 16, 12,  1, 29, 16,  0, 14, 27,
        4, 25,  3, 27, 27,  1, 25,  1, 14,  1, 27, 27, 15, 15, 13, 28, 25,
       18, 22, 15, 18, 28, 27,  5,  2,  4, 24, 16,  2, 15,  1, 17, 24, 17,
        0, 17, 16, 17,  2,  1, 14, 22,  3, 24, 16, 26,  4, 22, 23,  1,  4,
       22, 27, 15,  3,  2,  0,  2, 13, 29, 16, 12,  3, 27, 15,  5, 26,  0,
        3,  4, 15, 26,  1,  4, 15,  3, 14,  4, 17, 17,  2,  3,  8, 18,  4,
       18, 27, 17, 24, 24, 18,  2,  0, 25,  2, 15,  4,  0, 24, 28,  1,  1,
        3,  0, 18,  4, 12, 16,  8, 26,  0, 14, 27, 16, 14, 25, 13, 27,  2,
       12, 26, 16,  0, 25, 17, 27,  0,  3, 24, 28, 25, 16])

In [ ]:
Y_test

array([13, 17, 19,  6, 20, 20, 11, 19,  5, 27, 26,  6, 28, 27, 20,  8,  5,
        6, 20,  2,  6, 11, 17, 20,  4, 11,  6,  1, 19, 24, 21, 14,  6, 20,
       24, 19,  7, 15,  7, 19,  3, 10, 25, 19, 13, 21, 15, 23, 21,  1, 27,
       29,  7, 25,  3,  7,  1, 11,  4, 17, 16, 19,  6, 13, 10, 11,  8, 10,
        7, 25,  3, 10, 27,  1, 25,  1, 14,  6, 10,  7,  7, 15, 29, 28,  6,
       13, 19, 19, 29,  7, 10, 11,  2,  7, 19, 20, 11, 19, 20, 21, 24, 21,
       19, 21, 10, 21, 11, 20,  8, 19,  3, 12, 10, 26, 19, 19,  7,  1, 19,
       22, 10,  7, 11,  9, 19, 11, 18, 18, 20, 19,  3, 10, 19, 11, 22,  0,
        3,  7,  7, 26,  1, 19, 19, 11,  9,  4, 19, 17,  9,  5, 14, 29,  4,
       29, 10, 19, 24, 19, 29,  2, 11, 19,  9, 19, 19, 19, 24, 23,  6,  1,
       11, 19, 13,  4, 24, 20,  9, 22, 19, 14, 27, 20,  8,  6, 18,  7, 11,
       24, 19, 16, 11,  6, 17,  7, 19,  5, 19,  7, 19, 20])

In [63]:
new_flower=[[5.1,3.5,1.4,0.2]]
prediction=i_model.predict(new_flower)
prediction
print("predicted new flower species:",prediction)

predicted new flower species: [20]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [64]:
new_flower1=[[6.7,3.0,5.2,2.3]]
prediction1=i_model.predict(new_flower1)
prediction1
print("predicted new flower species:",prediction1)

predicted new flower species: [19]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [ ]:
# 3.BERNOULLI NAIVE BAYES

In [ ]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [ ]:
ds=pd.read_csv("rainfall.csv")
ds

,date,rainfall,temperature,humidity,wind_speed,weather_condition
0,2022-01-01,12.5,15.2,78.0,8.5,Rainy
1,2022-01-02,8.2,17.8,65.0,5.2,Rainy
2,2022-01-03,0.0,20.1,52.0,3.1,Sunny
3,2022-01-04,3.7,18.6,71.0,6.7,Rainy
4,2022-01-05,21.1,14.8,82.0,9.3,Rainy
5,2022-01-06,15.3,16.5,75.0,7.8,Rainy
6,2022-01-07,6.8,19.2,61.0,4.5,Rainy
7,2022-01-08,0.0,21.7,48.0,2.9,Sunny
8,2022-01-09,11.2,17.3,73.0,6.1,Rainy
9,2022-01-10,18.6,15.8,79.0,8.9,Rainy


In [ ]:
ds.isnull().sum()

,0
date,0
rainfall,1
temperature,1
humidity,1
wind_speed,1
weather_condition,1


In [ ]:
ds=ds.drop(53)
ds

,date,rainfall,temperature,humidity,wind_speed,weather_condition
0,2022-01-01,12.5,15.2,78.0,8.5,Rainy
1,2022-01-02,8.2,17.8,65.0,5.2,Rainy
2,2022-01-03,0.0,20.1,52.0,3.1,Sunny
3,2022-01-04,3.7,18.6,71.0,6.7,Rainy
4,2022-01-05,21.1,14.8,82.0,9.3,Rainy
5,2022-01-06,15.3,16.5,75.0,7.8,Rainy
6,2022-01-07,6.8,19.2,61.0,4.5,Rainy
7,2022-01-08,0.0,21.7,48.0,2.9,Sunny
8,2022-01-09,11.2,17.3,73.0,6.1,Rainy
9,2022-01-10,18.6,15.8,79.0,8.9,Rainy


In [ ]:
ds.isnull().sum()

,0
date,0
rainfall,0
temperature,0
humidity,0
wind_speed,0
weather_condition,0


In [55]:
ds=ds.drop("date",axis=1)
ds

,rainfall,temperature,humidity,wind_speed,weather_condition
0,12.5,15.2,78.0,8.5,Rainy
1,8.2,17.8,65.0,5.2,Rainy
2,0.0,20.1,52.0,3.1,Sunny
3,3.7,18.6,71.0,6.7,Rainy
4,21.1,14.8,82.0,9.3,Rainy
5,15.3,16.5,75.0,7.8,Rainy
6,6.8,19.2,61.0,4.5,Rainy
7,0.0,21.7,48.0,2.9,Sunny
8,11.2,17.3,73.0,6.1,Rainy
9,18.6,15.8,79.0,8.9,Rainy


In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [58]:
x=ds[["rainfall","temperature","humidity","wind_speed"]]
y=ds[["weather_condition"]]

In [59]:
r=BernoulliNB()


In [60]:
r.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB()

In [65]:
check=[[0.0,19.4,59.0,4.1]]
pr=r.predict(check)
pr
print("predicted new weather:",pr)

predicted new weather: ['Sunny']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


In [66]:
ch=[[11.6,19.1,65.0,5.1]]
p=r.predict(ch)
p
print("predicted new weather:",p)

predicted new weather: ['Rainy']


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(
